# Generated by Django 5.2.18 on 2026-10-09 12:11

import django.core.files.storage
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/lucas/OneDrive/Documents/projets/saphir-candidature/private_media')), upload_to='documents/%Y/%m/', verbose_name='fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('is_public_to_all_users', models.BooleanField(default=False, help_text='Si coché, tout utilisateur authentifié peut télécharger ce document.', verbose_name='accessible à tous les utilisateurs connectés')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Laissez vide si le document est destiné à tous les utilisateurs connectés.', related_name='accessible_documents', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs autorisés')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
