# Generated by Django 5.2.18 on 2026-10-09 13:53

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=documents.storage.PrivateR2Storage(), upload_to='documents/%Y/%m/', verbose_name='fichier'),
        ),
    ]
